channels:
- currentCSV: ibm-mongodb-operator.v1.1.1
  name: beta
- currentCSV: ibm-mongodb-operator.v1.1.2
  name: dev
- currentCSV: ibm-mongodb-operator.v1.1.1
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-mongodb-operator-app
