scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test 1 CR
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml"
    # `olm` tests configured to test 1 CR
    - olm:
        cr-manifest:
          - "./deploy/crds/operator.ibm.com_v1alpha1_mongodb_cr.yaml"
        csv-path: "./deploy/olm-catalog/ibm-mongodb-operator/0.0.1/ibm-mongodb-operator.v0.0.1.clusterserviceversion.yaml"
