- op: add
  path: /stages/0/tests/-
  value:
    entrypoint:
    - scorecard-test
    - basic-check-spec
    image: icr.io/operator-framework/scorecard-test:v1.1.0
    labels:
      suite: basic
      test: basic-check-spec-test
