apiVersion: operator.ibm.com/v1alpha1
kind: MongoDB
metadata:
  name: example-mongodb
spec:
  replicas: 3
  pullSecret: image-pull-secret
  imageRegistry: hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64


