apiVersion: operator.ibm.com/v1
kind: MongoDB
metadata:
  name: mongodb-sample
spec:
  replicas: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  pvc:
    resources:
      requests:
        storage: 10Gi
