apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbs.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: MongoDB
    listKind: MongoDBList
    plural: mongodbs
    singular: mongodb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MongoDB is the Schema for the mongodbs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MongoDBSpec defines the desired state of MongoDB
          properties:
            bootstrapImage:
              properties:
                tag:
                  type: string
              type: object
            imageRegistry:
              type: string
            initImage:
              properties:
                tag:
                  type: string
              type: object
            metricsImage:
              properties:
                tag:
                  type: string
              type: object
            mongoDBPass:
              type: string
            mongoDBUser:
              type: string
            replicas:
              type: integer
            storageClass:
              type: string
          type: object
        status:
          description: MongoDBStatus defines the observed state of MongoDB
          properties:
            storageClass:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
